apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-fmhw
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-fmhw
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-fmhw
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-fmhw
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-fmhw
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ftdy-tenant/rhtap-demo-app/hacbs-test-project-fmhw@sha256:3b3b5b6f58f71491d9be3114614d38f123e4c7c4d04295bfa6265ce9b180a8c1
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
