apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-fmhw
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ftdy-tenant/rhtap-demo-app/hacbs-test-project-fmhw@sha256:3b3b5b6f58f71491d9be3114614d38f123e4c7c4d04295bfa6265ce9b180a8c1
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
